### ISSUE TITLE
没法同步，一同步就出错是怎么回事？

### ISSUE THREAD

**Issue by dsilencedu** [megachweng/Dict2Anki#10]
一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "D:\Documents\Anki\addons\Dict2Anki.py", line 210, in sync
    self.detectLocalWordBookDB()
  File "D:\Documents\Anki\addons\Dict2Anki.py", line 258, in detectLocalWordBookDB
    ssl._create_default_https_context = ssl._create_unverified_context
AttributeError: 'module' object has no attribute '_create_unverified_context'

2.0版同步才会这样，3.0版直接没法加载，能不能帮我看看是怎么回事？谢谢，anki版本 2.0.36

**Comment by megachweng** [comment]
3.0无法加载可能是因为老版本的插件会生成`Dict2Anki.db`文件，然而并不能和新版本兼容。

所以请尝试删除collection.media目录下的`Dict2Anki.db`文件重新开启插件。

`AttributeError: 'module' object has no attribute '_create_unverified_context'`错误应该是你的Anki版本太旧，请尝试使用最新的Anki版本。

如果还有问题，feel free to submit another issue。
