### ISSUE TITLE
最近不能登陆欧陆词典，有道词典可以正常登陆

### ISSUE THREAD

**Issue by wangyuanwill** [megachweng/Dict2Anki#11]
一直都是使用欧陆词典，从2018年03月13日开使，不能登陆欧陆词典，点击登陆弹出'login failed'，而且发现生词本多次导入后会出现大量的重复卡片
![default](https://user-images.githubusercontent.com/36124721/37450048-796dc566-2867-11e8-8475-e870106ae143.PNG)

**Comment by ryanyangcode** [comment]
您好，我这边有同样的问题

**Comment by megachweng** [comment]
@wangyuanwill @ryanyangcode @YangShuqing  已经修复欧陆词典登录失败问题
同步重复问题可能是本地储存同步记录的数据库问题，请尝试删除colleciton.media里的Dict2Anki.db文件重新同步

**Comment by wangyuanwill** [comment]
@megachweng 感谢谢开发者及时修复，也感谢提供这么方便的插件！刚刚按上面的修改了，已经可以正常登陆了！

**Comment by wangyuanwill** [comment]
@megachweng 测试了几次，发现不能删除Dict2Anki.db文件，删除一次再导入一次单词就增加一倍，所以我觉得应该是保持这个文件从开始都不能被删除！以前出现重复的单词我想也是因为删除这个文件的原因，因为以前经常使用anki的“检查媒体”功能，然后anki就会提示Dict2Anki.db文件没有被任何版组使用，提示删除，然后就同其它的检查出来没有被使用的文件删除了，导致再一次导入单词是重复导入
