### ISSUE TITLE
修复windows 11下调欧路API不正常的问题

### ISSUE THREAD

**Issue by oneywang** [megachweng/Dict2Anki#113]
用的最新版本。

问题：
getTotalPage，getWordsByPage
这两个函数中调用 session.get时，url参数中的“data”参数并没有拼到url中，从而导致无法正常取词。

修复：
方法一：将 "data“改为”param“
r = self.session.get(
                url='https://my.eudic.net/StudyList/WordsDataSource',
                timeout=self.timeout,
                params=data
            )

方法二：将get改为使用session.post。
post能正常将”data“传出。

**Comment by Srun01** [comment]
macOS 同样有次问题，按方法二修复，确认可以用了

**Comment by Dilettante258** [comment]
非常感谢，修复好了！！！

**Comment by ChenBiRuoGuan** [comment]
厉害啊！！我昨天还在尝试修改错误！感谢！！
