### ISSUE TITLE
插件中欧路词典无法登陆

### ISSUE THREAD

**Issue by Liluoai** [megachweng/Dict2Anki#15]
系统版本：mac os sierra 10.12.6
anki版本：2.0.49

欧路词典在登录界面中，输入了正确的用户名和密码后依旧显示“Login Failed”，也无法同步生词本；有道词典则不受影响。

已经尝试过“删除插件并清除Dict2Anki.db文件再重装”，依旧如上。

另外ankiweb中也有两个用户反映同样问题，所以此问题应该不是个案。
<img width="469" alt="2018-03-18 15 51 50" src="https://user-images.githubusercontent.com/16595629/37563835-62c58790-2ac4-11e8-9d78-2b98255382c4.png">

**Comment by wangyuanwill** [comment]
看这个地方，这个问题刚刚解决关闭了，https://github.com/megachweng/Dict2Anki/issues/11

**Comment by megachweng** [comment]
@Liluoai Duplicate of #11 因为Eudict现在为https登录，刚刚已经修复

**Comment by Liluoai** [comment]
解决了，感谢！
