### ISSUE TITLE
欧陆词典使用邮箱登录不上

### ISSUE THREAD

**Issue by biueo** [megachweng/Dict2Anki#16]
我使用163邮箱注册的账号，登陆的时候老师login failed，不解

**Comment by megachweng** [comment]
请提供一下插件版本，anki版本，操作系统

**Comment by biueo** [comment]
anki版本 2.0.50，插件版本：3.0，操作系统MacOS 10.12.6

**Comment by megachweng** [comment]
你应该是从release里面下载的吧，问题之前已经修复Duplicate of #11
