### ISSUE TITLE
插件Dict2Anki 3.0登录失败 

### ISSUE THREAD

**Issue by dashimu** [megachweng/Dict2Anki#19]
你好，用的是Mac版本，升级了 anki 最新版本，Dict2Anki 3.0 , 用欧陆词典登录失败，请问原因？

**Comment by dashimu** [comment]
用有道词典登录成功，难道是 欧陆词典的 api 有问题？

**Comment by megachweng** [comment]
请下载最新master分支的代码

**Comment by dashimu** [comment]
谢谢， 已经解决！
