### ISSUE TITLE
发音

### ISSUE THREAD

**Issue by yuanzhiqee** [megachweng/Dict2Anki#2]
请问能不能在卡片中加上发音？

**Comment by megachweng** [comment]
发音功能以后会考虑集成，请留意项目更新

**Comment by megachweng** [comment]
你好，我是Dict2Anki <https://github.com/megachweng/Dict2Anki/releases>
的开发者，新版本的插件已经支持同步发音，欢迎使用

PS：

如果使用过旧版本的插件同步过单词本，请删除并重新同步，否则只有新同步的单词才会有发音

yuanzhiqee <notifications@github.com>于2017年10月30日周一 下午9:27写道：
