### ISSUE TITLE
Mac Anki 2.0.50 插件一直显示 wait...

### ISSUE THREAD

**Issue by ffr** [megachweng/Dict2Anki#20]
请求帮助，用了两种方式安装均卡在 waiting （ sync 按钮变成 wait... ) 貌似之前的版本成功过，而且很快。更新了一下，现在不行了。已删除之前同步的 deck，还是不行。
<img width="584" alt="screen shot 2018-03-22 at 12 16 15 pm" src="https://user-images.githubusercontent.com/1229771/37750998-dd4fb50e-2dca-11e8-99b0-469ab56cec96.png">

**Comment by ffr** [comment]
Eudict 登录失败...

**Comment by wangyuanwill** [comment]
欧路词典作者前几天因为登陆失败更新过，可以看看前面的贴子！有道词典刚刚试了一下登陆和同步都是正常的！

**Comment by dashimu** [comment]
请下载最新master分支的代码  ， 可以解决Eudict 登录失败的问题 @ffr
