### ISSUE TITLE
网易有道词典登陆失败

### ISSUE THREAD

**Issue by HappyIngrid** [megachweng/Dict2Anki#24]
试了很多次，都是login failed，因为担心是密码输错了，我甚至在有道词典新建了个账号，但是username无论是输邮箱还是输用户名，都登陆失败，手机上的有道词典却可以登上，截图已贴在下方，麻烦大神看看怎么解决，谢谢

![b 1sgr ni 3cvldktl_n_2](https://user-images.githubusercontent.com/38210893/38493227-03024ac0-3c24-11e8-90f5-5e45701b652d.png)
![x0wil f5u1rn00ixf dhned](https://user-images.githubusercontent.com/38210893/38493356-7a8584b8-3c24-11e8-8b29-416bdfa8e86a.png)

**Comment by HappyIngrid** [comment]
电脑系统 Windows8 企业版

**Comment by megachweng** [comment]
你好，插件是不是直接在anki中输入插件号码安装的？如果是的话请下载github master分支的代码覆盖一下，ankiweb上的还没有更新

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HappyIngrid** [comment]
已解决，谢谢大神！

**Comment by HappyIngrid** [comment]
大神，我重新下载了插件所有的代码装了一遍，现在已经可以运行了，谢谢您！
