### ISSUE TITLE
导入欧陆的生词本时，有没有办法使用自定义的字典？

### ISSUE THREAD

**Issue by nmly** [megachweng/Dict2Anki#27]
发现欧陆自动使用的字典挺多问题，不少发音错的，中文的解释也有些很奇怪的，自动导入的例句都是不够友好，有些翻译有问题，甚至英文例句里还发现了有个拼音混进去。

有办法使用自定义的字典导入吗？

**Comment by nmly** [comment]
btw, 欧陆词典里发音是没问题，但是不知道为啥导入生词本到ANKI里发音就变了。

**Comment by megachweng** [comment]
所有单词的发音例句解释都是用的有道开放api获取，所以会有不同

**Comment by nmly** [comment]
原来是有道的词典，这么烂，幸亏一直没用有道。。。
例句就不说了，比如 chutzpah，发音错到姥姥家了。

有办法用其他字典或者本地字典吗？

**Comment by megachweng** [comment]
你可以把想用的字典API发给我
添加自定义查询源的功能，加到版本迭代中

**Comment by nmly** [comment]
https://github.com/jokermonn/-Api/blob/master/BingDic.md

这个BING的API可用吗？

oxford dictionary 提供的免费API似乎有流量限制，只适合个人使用。自定义API的功能，容易搞出来吗？

**Comment by megachweng** [comment]
```https://cn.bing.com/api/v7/dictionarywords/search?q=calculator&appid=371E7B2AF0F9B84EC491D731DF90A55719C7D209&mkt=zh-cn&pname=bingdict&img=1```
你发的api已经失效了，抓了下bingApp，调的是这个接口，有个appid参数必要参数，不知道会不会失效，过几天测试一下再看吧
