### ISSUE TITLE
【已解决】今天试了下，0个词添加，不知为何

### ISSUE THREAD

**Issue by gdd111** [megachweng/Dict2Anki#28]
如题

**Comment by megachweng** [comment]
请提供更多细节

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gdd111** [comment]
【已解决】
第一次同步结束有提示，但没仔细看，应该是——添加了x个单词，删除了x个单词。
之后的同步都失败，应该是同步记录中显示已添加，所以对比之后，添加0个单词。
删除插件重装解决问题，注意要在everything中搜索dict2anki，会出dict2anki.db这个文件也要删除，才能重装成功（猜测同步信息在这文件里）。
之后就ok了。
