### ISSUE TITLE
本地卡片删除后无法再同步

### ISSUE THREAD

**Issue by Lighsark** [megachweng/Dict2Anki#29]
例
1 从欧路生词本同步单词abandon到anki
2 anki中删除卡片abandon
3 再次同步 No word has been lookupped

**Comment by megachweng** [comment]
是这样的，目前只能从欧陆中把abandon这个单词移除，再同步就会移除，如果直接在anki中删除的话，因为这个单词还在插件的数据库中所以不会添加

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by megachweng** [comment]
可以先在欧陆中删除这个单词，同步一次，在欧陆中添加完后再同步一次解决

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
