### ISSUE TITLE
在未加入新词的情况下点同步出错

### ISSUE THREAD

**Issue by JerryPang** [megachweng/Dict2Anki#3]
您好，
如果上次在anki同步成功后，在有道和欧路的单词本未增加任何新词的情况下，此时再点同步，会直接导致anki强制关闭
比如说我第一次同步成功后，马上再点一次同步，就一定会导致软件崩溃。
测试环境 win10
谢谢！

**Comment by JerryPang** [comment]
还有个问题，在win10下同步有道会提示Error 01:Youdao wordbook conflict!
我把225行
 showInfo("Error 01:Youdao wordbook conflict!")
改成
self.youdaoDB = youdaoDB + "\\" + yo[0] + "\local"
就正常了。

**Comment by megachweng** [comment]
@JerryPang Error01一般是因为你以前登陆过不同的网易ID，即使退出登陆，原先账号的单词本依然会保留，所以不知道读取那个ID下的单词本

**Comment by JerryPang** [comment]
@megachweng 谢谢，试了下确实是这个原因导致的，第一个问题比较恼火，软件崩溃会导致anki里刚添加的单词全部丢失。
