### ISSUE TITLE
欧路词典无法同步，但有道可以

### ISSUE THREAD

**Issue by lizyn** [megachweng/Dict2Anki#32]
macOS，Anki 2.0.50，试过 3.0 版本和 master 分支下的最新代码，情况类似；没有看到任何报错。表现为：

欧路词典可以正常登陆，但无法同步生词列表，一直停留在如下界面。
<img width="695" alt="eudict" src="https://user-images.githubusercontent.com/26119970/42204983-c526d65e-7ed5-11e8-9921-5f4f48250c71.png">

而有道词典可以正常登陆和同步
<img width="695" alt="youdao" src="https://user-images.githubusercontent.com/26119970/42204991-ca41f268-7ed5-11e8-8d8c-cb60698d7a66.png">

而我平时都是用的欧路词典，所以...

**Comment by megachweng** [comment]
这种情况可以试一下把dict2anki.db文件删除，重新安装插件
打算抽时间重构一下这个插件，当时的编码水平太垃圾了

**Comment by lizyn** [comment]
删除 Dict2Anki.db 和 Eudict.cookie 文件后重装试过，还是不大行，等你重构后我再试试好了，😂
