### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by onionycs** [megachweng/Dict2Anki#33]
这个插件应该要把查询到的单词的所有词性和所有的意思都录入到卡片上 
现在的definition最好像sentence和phrase一样，
有definition1.
definition2.
definition3.......
现在的V3版本只会lookup第一个，不能记住所有的意思，让人有点失望...

**Comment by megachweng** [comment]
之前有想过把所有释义放上去，但是一张卡片就会显得很长。你也可以稍微修改一下代码就能实现，因为查询时已经把获取到了所有内容，只是我设定了最多只添加3个。
