### ISSUE TITLE
看不见UI。因为没有正确安装吗？

### ISSUE THREAD

**Issue by anewbrand** [megachweng/Dict2Anki#34]
已按照说明页面的指示，尝试了两种安装方法。都无法找到其UI在哪里，找不到密码、同步界面。
在how to use页面，无法理解是如何从eudic词典的界面，变成UI界面的。
在Anki的addon里面，只能看到“PluginEntry”。
Anki版本 2.0.32，安装在D盘。

请问，是怎么回事？

**Comment by megachweng** [comment]
插件安装目录下面应该又一个error.log日志，如果有的话请贴上来看一下

**Comment by anewbrand** [comment]
感谢回复。
我看过插件所在目录、anki程序安装目录、磁盘搜索，都没有这个error日志。

**Comment by anewbrand** [comment]
还是没有error*.log文件产生。
不过惊喜的是，发现了：工具》"import your wordbook"菜单项！成功登陆并且导入了一些生词。非常感谢！
但遗憾的是，不小心中断之后，再重新sync，一直处于“waiting”状态。
请问有sync中断再重启，有什么帮助文件吗？多谢~

**Comment by anewbrand** [comment]
好的。了解了。多谢解答。真是非常有用的addon，帮了大忙。
