### ISSUE TITLE
请问同步生词表所使用的词典是哪个？

### ISSUE THREAD

**Issue by anewbrand** [megachweng/Dict2Anki#36]
请问同步生词表所使用的词典是哪个？可以自己选择吗？
我eudic设置的词典是Collins COBUILD BL，但是同步到anki的词典解释不是Collins。希望可以使用Collins的解释。

**Comment by megachweng** [comment]
调用有道词典公共Api查询的，查询时没有你自定义的词组，他就只查了第一个

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by megachweng** [comment]
[v5.0.0](https://ankiweb.net/shared/info/1284759083)版本已经发布，后续用户自定义词典源功能会在此版本上添加，感觉支持
