### ISSUE TITLE
登陆账号后，卡在了wait的这步，请问是什么问题呀

### ISSUE THREAD

**Issue by GarboHeart** [megachweng/Dict2Anki#38]
https://ws1.sinaimg.cn/large/0069RVTdly1fuo3euz1i8j30we0medi8.jpg

**Comment by GarboHeart** [comment]
突然想到是因为没有笔记模板么 那这个模板又在哪里呢

**Comment by BenMing** [comment]
> 突然想到是因为没有笔记模板么 那这个模板又在哪里呢



> 我也有同样的问题

应该是安装 add-on 的时候就自动安装了，新建一个 deck 就可以看到一个叫 Dict2Anki 的模板。

**Comment by megachweng** [comment]
[v5.0.0](https://ankiweb.net/shared/info/1284759083)版本已经发布（只支持Anki2.1.x），已经修复此类问题
