### ISSUE TITLE
欧路词典网络异常

### ISSUE THREAD

**Issue by joexzh** [megachweng/Dict2Anki#45]
用2.0 Anki desktop和插件出现HTTP code 500, 换2.1也是网络异常.
接口出问题了吗?
> 2.1的log
```
2018-12-05 18.38.26 :
cookie有效，直接使用cookie 

2018-12-05 18.38.26 :
获取单词本 
2018-12-05 18.38.30 :
网络异常 

2018-12-05 18.38.30 :
远程单词本:[] 


2018-12-05 18.39.33 :
没有需要查询的单词。 
```

**Comment by megachweng** [comment]
能提供完整日志吗？

**Comment by megachweng** [comment]
应该是欧陆词典的服务器有问题，或者是你本地是不是开了什么代理而且失效，在其他环境测试没有问题

**Comment by joexzh** [comment]
天哪, 多次尝试之后, 这个接口被限制数量了, length大于4341就爆了
[https://my.eudic.net/StudyList/WordsDataSource?length=100000000&categoryid=-1](https://my.eudic.net/StudyList/WordsDataSource?length=100000000&categoryid=-1)

**Comment by megachweng** [comment]
这里直接写死了一个很大的值，为了获取全部的单词，可能一次获取太多单词被服务端拒绝了。
这里我现在去做一下分段，你再试一下。

PS：查询单词API每天似乎也是有数量限制的，如果单词量很大估计也会出错，先解决这个问题吧

**Comment by joexzh** [comment]
@megachweng 已试用, 能够正常运行了.

**Comment by megachweng** [comment]
好的，升级的提示框，在版本发布之后会消失，
感谢支持，star可以点一个😄
