### ISSUE TITLE
cookie无效，重新登录

### ISSUE THREAD

**Issue by fengbeibei** [megachweng/Dict2Anki#51]
登录欧陆和有道都显示cookie无效，重新登录，使用新建的desk，模板也是Dict2Anki_NEW
![image](https://user-images.githubusercontent.com/19942192/53717340-d1f2ac00-3e92-11e9-9d0d-e252e6419ab7.png)

**Comment by fengbeibei** [comment]
也试过了删除Anki重新安装，没作用。另外，每次使用插件都会导致软件崩溃
![image](https://user-images.githubusercontent.com/19942192/53717463-34e44300-3e93-11e9-97e5-3339ec7dba54.png)

**Comment by megachweng** [comment]
先确定一下是不是身份信息输入有误
如果确认无误，到 [有道单词本](http://account.youdao.com/login?service=dict&back_url=http://dict.youdao.com/wordbook/wordlist%3Fkeyfrom%3Dnull)页面登陆一下，有道有个机制，多次登陆后会禁止登陆，这也是为什么要保存Cookie的原因

**Comment by fengbeibei** [comment]
解决了，不小心输错了邮箱，半天都没看出来。。谢谢！
