### ISSUE TITLE
导入anki的模板能不能保持2.0的样子啊，现在的这种没有phrase，好不习惯。

### ISSUE THREAD

**Issue by kwingart** [megachweng/Dict2Anki#52]
导入anki的模板能不能保持2.0的样子啊，现在的这个版本发音按钮在最下面，而且没有phrase，好不习惯。谢谢作者分享。

**Comment by megachweng** [comment]
6.0.0即将发布，短语字段会恢复，感谢支持！

**Comment by kwingart** [comment]
收到，感谢分享。
我看了6.0的style，还好。
不过还是最喜欢原来3.x的那个排版和风格，短语也是精选的，没有现在这么多；现在字稍微大了些，感觉没原来的舒服。能通过自己改模板来缩小字体么？anki的设置不起作用，不知道为什么。
