### ISSUE TITLE
从欧路同步不能指定单词本吗

### ISSUE THREAD

**Issue by luwantaoChina** [megachweng/Dict2Anki#59]
能实现指定从欧路的某个单词本中同步吗？我刚用这个插件，试了一下这个同步功能，把所有单词本的单词都同步过来了，这样就比较尴尬了。抱歉，我看新版本的软件似乎已经有这个功能了，但我是用旧版的软件

**Comment by megachweng** [comment]
指定单词本功能已经在6.0版本添加，请更新一下插件

**Comment by luwantaoChina** [comment]
> 
> 
> 指定单词本功能已经在6.0版本添加，请更新一下插件。
感谢回复。我是个初学者，anki2.0版本目前教程比较多，anki2.1用了一下感觉不太会用。而6.0版本的插件得在anki2.1上才能运行吧？

**Comment by megachweng** [comment]
建议升级anki2.1版本，插件后续的功能更新都是基于2.1版本

**Comment by megachweng** [comment]
2.1的稳定性也高很多

**Comment by luwantaoChina** [comment]
好的，谢谢
