### ISSUE TITLE
win10 下无法从欧路词典中导入

### ISSUE THREAD

**Issue by luwantaoChina** [megachweng/Dict2Anki#60]
可以完成从欧路中取词，从有道查词。![20190606181332.png](https://csdn-blog-1258434200.cos.ap-shanghai.myqcloud.com/undefined20190606181332.png)
但是最后，开始同步这步出错，报错：[06/06/2019 18:55:27][   ERROR] -- 'term' - (dict2Anki)Traceback (most recent call last):  File "anki\notes.py", line 93, in _fieldOrdKeyError: 'term'During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "C:\Users\14747\AppData\Roaming\Anki2\addons21\1284759083\addon\addonWindow.py", line 452, in on_syncBtn_clicked    addNoteToDeck(deck, model, currentConfig, wordItemData)  File "C:\Users\14747\AppData\Roaming\Anki2\addons21\1284759083\addon\noteManager.py", line 123, in addNoteToDeck    newNote['term'] = oneQueryResult['term']  File "anki\notes.py", line 101, in __setitem__  File "anki\notes.py", line 95, in _fieldOrdKeyError: 'term'
![20190606185709.png](https://csdn-blog-1258434200.cos.ap-shanghai.myqcloud.com/undefined20190606185709.png)

**Comment by megachweng** [comment]
请问black_cat::earlyRead这个盘组中是否含有其他卡片

**Comment by luwantaoChina** [comment]
您好，我如果，在插件中直接写一个新的牌组然后点击同步。anki中会新建一个牌组，但是这个牌组中同样没有卡片，日志中仍然报错：[06/06/2019 21:34:52][   ERROR] -- 'term' - (dict2Anki)Traceback (most recent call last):  File "anki\notes.py", line 93, in _fieldOrdKeyError: 'term'During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "C:\Users\14747\AppData\Roaming\Anki2\addons21\1284759083\addon\addonWindow.py", line 452, in on_syncBtn_clicked    addNoteToDeck(deck, model, currentConfig, wordItemData)  File "C:\Users\14747\AppData\Roaming\Anki2\addons21\1284759083\addon\noteManager.py", line 123, in addNoteToDeck    newNote['term'] = oneQueryResult['term']  File "anki\notes.py", line 101, in __setitem__  File "anki\notes.py", line 95, in _fieldOrdKeyError: 'term'

**Comment by megachweng** [comment]
看起来应该是这个模版生成的有问题，能否帮忙调试一下，假期准备发布新版本，非常感谢你的帮助
调试方法 `Ctrl+Shift+ ;`打开debug console
上方输入
```python
print("Fields",model['flds'])
print("============================")
deck = mw.col.decks.get(mw.col.decks.id("这里改成刚同步失败的牌组名"))
print(deck)
```
<img width="755" alt="Screen Shot 2019-06-07 at 12 48 09 AM" src="https://user-images.githubusercontent.com/18111773/59050885-1ccef600-88be-11e9-9eb0-9e7c1724e931.png">

然后CTRL + 回车执行

**Comment by luwantaoChina** [comment]
没问题的，非常感谢您开发这么实用的插件。我刚才想同步的是这个名为new的牌组：
![20190607005951.png](https://csdn-blog-1258434200.cos.ap-shanghai.myqcloud.com/undefined20190607005951.png)
输出的文本内容如下：
```>>> model = mw.col.models.byName('Dict2Anki-v6.0.0')
... print("Fields",model['flds'])
... print("============================")
... deck = mw.col.decks.get(mw.col.decks.id("new"))
... print(deck)
Fields []
============================
{'newToday': [25, 0], 'revToday': [25, 0], 'lrnToday': [25, 0], 'timeToday': [25, 0], 'conf': 1, 'usn': -1, 'desc': '', 'dyn': 0, 'collapsed': False, 'extendNew': 10, 'extendRev': 50, 'name': 'new', 'id': 1559840090662, 'mod': 1559840090}
```

**Comment by megachweng** [comment]
模版创建有异常，字段为空。请尝试一下删除插件的模版:Dict2Anki-v6.0.0，重新同步
同步时插件会自动生成模版，然后确保模版的 Fields 为 图三所示

<img width="226" alt="Screen Shot 2019-06-07 at 1 20 47 AM" src="https://user-images.githubusercontent.com/18111773/59052894-be584680-88c2-11e9-8fdb-4892a678db53.png">
<img width="508" alt="Screen Shot 2019-06-07 at 1 20 56 AM" src="https://user-images.githubusercontent.com/18111773/59052900-c0baa080-88c2-11e9-9a41-d52b5fecb9df.png">
<img width="524" alt="Screen Shot 2019-06-07 at 1 21 11 AM" src="https://user-images.githubusercontent.com/18111773/59052906-c3b59100-88c2-11e9-9f86-2b6be39b3689.png">

**Comment by luwantaoChina** [comment]
非常感谢，问题已经解决。

**Comment by megachweng** [comment]
不客气，但是很好奇一开始为什么模版会创建失败

**Comment by luwantaoChina** [comment]
有可能是我之前是安装了anki2.0版本，然后也装了这个插件。然后卸载了2.0，安装上2.1，是不是没有卸载干净，之前模板或者配置之类起了冲突。

**Comment by megachweng** [comment]
看来同步前还需要插件检查一遍，已经加入 7.0.0的 [pinboard](https://github.com/megachweng/Dict2Anki/projects/3)
