### ISSUE TITLE
win10 下必应api 查词失败

### ISSUE THREAD

**Issue by luwantaoChina** [megachweng/Dict2Anki#61]
您好，我这边可以正常使用有道api查词，但必应api查词失败。
![20190607014347.png](https://csdn-blog-1258434200.cos.ap-shanghai.myqcloud.com/undefined20190607014347.png)
日志如下：
![20190607014539.png](https://csdn-blog-1258434200.cos.ap-shanghai.myqcloud.com/undefined20190607014539.png)
```
[   ERROR] -- Expecting value: line 1 column 1 (char 0) - (dict2Anki.queryApi.bing)Traceback (most recent call last):  File "C:\Users\14747\AppData\Roaming\Anki2\addons21\1284759083\addon\queryApi\bing.py", line 86, in query    query_result = cls.parser(rsp.json(), word).result  File "lib\site-packages\requests\models.py", line 897, in json  File "json\__init__.py", line 354, in loads  File "json\decoder.py", line 339, in decode  File "json\decoder.py", line 357, in raw_decodejson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by megachweng** [comment]
是的必应词典使用的第三方的API(http://xtk.azurewebsites.net/BingDictService.aspx)，他的站点似乎已经关闭了，所以暂时不能使用,下一个版本再考虑添加一些新的API
https://zhuanlan.zhihu.com/p/22421123
