### ISSUE TITLE
词典的模板能优化一下吗？

### ISSUE THREAD

**Issue by luwantaoChina** [megachweng/Dict2Anki#62]
您好，您开发的这个插件非常实用，我非常喜欢。但是感觉您目前的这个模板太单一了，能不能丰富一下细节，比如加一些词频统计，然后优化一下背景色之类的。比如加入 the little dict; 
![20190610174130.png](https://csdn-blog-1258434200.cos.ap-shanghai.myqcloud.com/undefined20190610174130.png)
或者允许用户自定义模板，然后用本地词典生成卡片之类的。

**Comment by megachweng** [comment]
7.0.0版本的可定制性会很高，还在开发当中
