### ISSUE TITLE
Windows 10, Anki2.1 卡片编辑时, 例句和短语显示不正常, 它们不在编辑框中.

### ISSUE THREAD

**Issue by zhoujin7** [megachweng/Dict2Anki#64]
Windows 10, Anki2.1 卡片编辑时, 例句和短语显示不正常, 它们不在编辑框中.
如图所示.
![https://img.vim-cn.com/9e/1ededdf07874565eb35c045ee2a0dbb3886fb7.png](https://img.vim-cn.com/9e/1ededdf07874565eb35c045ee2a0dbb3886fb7.png) 
![https://img.vim-cn.com/d7/ffd386dee43e60c10ee8b2ff6d570d8ad762b2.png](https://img.vim-cn.com/d7/ffd386dee43e60c10ee8b2ff6d570d8ad762b2.png)

**Comment by megachweng** [comment]
也发现了这个问题，问题是Anki无法正确识别html table 内容导致，暂无解决办法，下一个版本全部用JS渲染应该可以解决这种问题。
