### ISSUE TITLE
About 英英释义(English-English) function

### ISSUE THREAD

**Issue by deluser8** [megachweng/Dict2Anki#68]
@megachweng 

I have almost finished 英英释义 function. May I discuss the UI design with you?

There are two options we may apply.
1. Show nothing different in UI,  "释义" checkbox will include English-Chinese and English-English dictionary by default.
2. Show another 2 Checkboxes with name of "中英释义" and "英英释义".

Thank you for your reply.

**Comment by megachweng** [comment]
Feel free to PR

**Comment by deluser8** [comment]
Thank you very much and I have PR.
