### ISSUE TITLE
最多能导入多少单词？

### ISSUE THREAD

**Issue by linonetwo** [megachweng/Dict2Anki#71]
我导入后发现 a-z 的单词，只有 a-d 的导入了，后面的都丢了。

再次导入后只会重复导入单词。

我修改了卡片模板让它仅在显示答案时才显示图片，有关系吗？

**Comment by megachweng** [comment]
麻烦提供更多详细日志信息，才好判断

**Comment by linonetwo** [comment]
抱歉误报了…原来是我的有道词典莫名其妙退出登录了，就没有同步到云端，所以新加的单词都只在本地。
