### ISSUE TITLE
对于单词模版的样式有没有兴趣改改？

### ISSUE THREAD

**Issue by wd** [megachweng/Dict2Anki#74]
我看比如例句用的是 table ，改成比如 <div><ol><li> 的形式会比较容易通过 css 控制样式，现在例句都是黑乎乎的一片，至少加一个 1,2,3 这样的编号，以及把翻译设置成不一样的颜色，应该会好很多。

例如欧陆这个样式看起来是不是舒服一点。

![image](https://user-images.githubusercontent.com/58177/68740405-f019ca00-0625-11ea-93b3-0ca80ca9dd7b.png)

没有冒然提 PR，想看看作者的想法。

**Comment by megachweng** [comment]
[7.0.0分支](https://github.com/megachweng/Dict2Anki/tree/7.0.0)中，Anki的model中添加里[content](https://github.com/megachweng/Dict2Anki/blob/7.0.0/addon/constants.py#L8)字段，保存获取数据的Json文本
再在template中用JS解析json文本直接渲染卡片[详见](https://github.com/megachweng/Dict2Anki/blob/7.0.0/addon/template/front.html#L31)

**Comment by megachweng** [comment]
样式是有打算在这个版本发布时大改一下，感觉你的PR

**Comment by wd** [comment]
明白了。

**Comment by wd** [comment]
我简单改了一下样式，效果见下面图

![image](https://user-images.githubusercontent.com/58177/68746462-991af180-0633-11ea-8983-2c352abb31bd.png)

如果有想要使用的，可以使用  https://github.com/wd/Dict2Anki/blob/beautify/addon/noteManager.py  这个文件替换掉  `~/Library/Application Support/Anki2/addons21/1284759083/addon` 目录下面的。这个目录可以通过 `Tools -> Add-ons -> View Files` 找到。

**替换之后需要先删除原来的卡片模版，这个操作会导致原来通过这个插件添加的词组和学习进度全部丢失。**

重新打开 Anki 重新同步一次数据就可以了。
