### ISSUE TITLE
Release tag 似乎起的不对，导致现在每次打开都会提示升级，即使已经是最新的版本

### ISSUE THREAD

**Issue by wd** [megachweng/Dict2Anki#76]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/58177/69036251-6f414080-0a20-11ea-927e-2c9eb8053c5f.png">

应该是名字上面少了一个 `v` 。

`[18/11/2019 16:25:43][    INFO] -- 检查到新版本:6.1.1--添加欧陆词典查询API`

<img width="379" alt="image" src="https://user-images.githubusercontent.com/58177/69036308-90a22c80-0a20-11ea-8b29-8f51b2f09a9a.png">

**Comment by megachweng** [comment]
感谢反馈，已经修复

**Comment by megachweng** [comment]
判断版本号的方法似乎需要优化一下
