### ISSUE TITLE
我的欧路词典是通过微博登陆的, 但是好像插件的登陆选项不支持第三方登陆,是吗?

### ISSUE THREAD

**Issue by Harry-Wu** [megachweng/Dict2Anki#8]
我的欧路词典账号是通过第三方登陆的, 但是插件没有这个登陆选项，这样就没法导入生词本，是吗?
还是说有其他入口我没发现？

**Comment by megachweng** [comment]
非常抱歉，暂时只支持邮箱登录，会在下个版本添加第三方登录支持。

可以考虑用邮箱注册一个账号导入原账号的单词，再用插件同步。

非常感谢你的反馈。

**Comment by metayoung** [comment]
你可以把账号绑定邮箱，然后在登陆页面通过忘记密码来设置密码，然后就可以通过邮箱登陆了。

**Comment by Harry-Wu** [comment]
@metayoung 好的，谢谢提醒，晚上回去试试
