### ISSUE TITLE
网易有道词典无法同步

### ISSUE THREAD

**Issue by MeYoungW** [megachweng/Dict2Anki#80]
同步时不出现我的单词本里的分组，一直在刷新
![image](https://user-images.githubusercontent.com/35915317/74940457-694a6980-542c-11ea-95dc-6f6251dc4b8d.png)
网易有道词典版本
![image](https://user-images.githubusercontent.com/35915317/74940531-854e0b00-542c-11ea-8f42-dbc1be3cb136.png)
Dict2Anki也检查更新版本 应该是最新版https://ankiweb.net/shared/info/1284759083
这个问题出现是有道的问题吗？要我冲会员哈哈？
感觉应该是无法获取我的单词本了，希望能帮忙解决一下，谢谢

**Comment by MeYoungW** [comment]
试了一下欧陆可以，但是切回用有道不像欧陆需要登录信息
平时pc有用v2rayn会不会有影响

**Comment by Chen-Isaac** [comment]
我今天也遇到了同样的问题，有道的单词本分组无法出现。我用手机热点也是一样的情况，应该和v2rayn没有关系。是不是有道API有什么更新？

**Comment by wd** [comment]
不能同步的话，贴一下日志里面的内容呢？那个对话框有一个 ‘日志’

**Comment by megachweng** [comment]
原因目前看起来是未登录访问 `http://dict.youdao.com/wordbook/wordlist` 这个地址并没有redirect 到 `account.youdao.com/login`这个地址，Cookie是否有效的判断通过了，所以无法获取词组

https://github.com/megachweng/Dict2Anki/blob/c8f2f52f507dfc4766141157243bd42e7a1e7abb/addon/dictionary/youdao.py#L37

**Comment by megachweng** [comment]
youdao更新了API，返回json数据格式更加友好了

**Comment by megachweng** [comment]
已经修复
https://github.com/megachweng/Dict2Anki/blob/c835b2113601e607651b917d978c4717fec5c239/addon/dictionary/youdao.py#L38-L39
