### ISSUE TITLE
这个插件怎么用？为什么 我的一直提示登录？

### ISSUE THREAD

**Issue by NewOneTcm** [megachweng/Dict2Anki#83]
这个插件怎么用？为什么 我的一直提示登录？
我登录了，点reload也没有反应，重新点查询，又要登录，
求助
![QQ图片20200609220829](https://user-images.githubusercontent.com/49179435/84158004-f67a0280-aa9d-11ea-9b57-170ab8b9b063.jpg)

**Comment by cythb** [comment]
我也遇到这个问题了，这是我修复好的版本。你可以试下看看有没有问题。 #84

**Comment by megachweng** [comment]
FIXED #84
