### ISSUE TITLE
请问欧陆词典能否实现同步一个句子的功能

### ISSUE THREAD

**Issue by daxiaaaaa** [megachweng/Dict2Anki#98]
就是现在在欧陆词典中 查询一句话，出来的是“网络释义”，然后点收藏，同步到anki中，句子本身是可以同步过去，但是网络释义同步不了

**Comment by megachweng** [comment]
这个插件最开始目的是只同步单词本中的内容，查词是个附加功能，可能以后会加上自定义注释获取吧。
